# Generated by Django 5.1.5 on 2025-01-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=17, verbose_name='Номер телефона')),
                ('code', models.CharField(max_length=4, verbose_name='Код подтверждения')),
                ('attempts', models.IntegerField(default=0, verbose_name='Количество попыток')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
            ],
            options={
                'verbose_name': 'Код подтверждения',
                'verbose_name_plural': 'Коды подтверждения',
                'ordering': ['-created_at'],
            },
        ),
    ]
