# Generated by Django 5.1.5 on 2025-01-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0003_alter_onetimecode_options_alter_onetimecode_attempts_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
