# Generated by Django 5.1.5 on 2025-01-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onetimecode',
            options={'verbose_name': 'one time code', 'verbose_name_plural': 'one time codes'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Required. Format: +7XXXXXXXXXX', max_length=20, unique=True, verbose_name='phone number'),
        ),
    ]
