# Generated by Django 5.1.5 on 2025-01-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0005_alter_onetimecode_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onetimecode',
            options={'ordering': ['-created_at'], 'verbose_name': 'one time code', 'verbose_name_plural': 'one time codes'},
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='attempts',
            field=models.IntegerField(default=0, help_text='Number of verification attempts', verbose_name='verification attempts'),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='code',
            field=models.CharField(help_text='4-digit verification code', max_length=4, verbose_name='verification code'),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='expires_at',
            field=models.DateTimeField(help_text='Code expiration time', verbose_name='expires at'),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the code has been verified', verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='phone',
            field=models.CharField(help_text='Phone number in format: +7XXXXXXXXXX', max_length=20, verbose_name='phone number'),
        ),
        migrations.AddIndex(
            model_name='onetimecode',
            index=models.Index(fields=['phone', 'is_verified'], name='login_auth__phone_f50aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='onetimecode',
            index=models.Index(fields=['created_at'], name='login_auth__created_d0ac3c_idx'),
        ),
    ]
