# Generated by Django 5.1.5 on 2025-01-30 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='announcementcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='announcements.announcementcategory', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='announcements.announcementcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='announcementimage',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_images', to='announcements.announcement', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='lostfoundannouncement',
            name='announcement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found_details', to='announcements.announcement', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='lostpet',
            name='announcement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lost_pet', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='matingannouncement',
            name='announcement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mating_details', to='announcements.announcement', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='serviceannouncement',
            name='announcement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='announcements.announcement', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='matingannouncement',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mating_profiles', to='announcements.animalannouncement', verbose_name='Животное'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_at'], name='announcemen_created_40a59f_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['category'], name='announcemen_categor_767517_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['author'], name='announcemen_author__0e981a_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_premium'], name='announcemen_is_prem_c647cc_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active'], name='announcemen_is_acti_a26055_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfoundannouncement',
            index=models.Index(fields=['type'], name='announcemen_type_a184fb_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfoundannouncement',
            index=models.Index(fields=['animal_type'], name='announcemen_animal__d8f35f_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfoundannouncement',
            index=models.Index(fields=['date_lost_found'], name='announcemen_date_lo_e897fb_idx'),
        ),
        migrations.AddIndex(
            model_name='lostpet',
            index=models.Index(fields=['status'], name='announcemen_status_37af19_idx'),
        ),
        migrations.AddIndex(
            model_name='lostpet',
            index=models.Index(fields=['date_lost_found'], name='announcemen_date_lo_2b4152_idx'),
        ),
        migrations.AddIndex(
            model_name='lostpet',
            index=models.Index(fields=['is_active'], name='announcemen_is_acti_ab0c26_idx'),
        ),
        migrations.AddIndex(
            model_name='matingannouncement',
            index=models.Index(fields=['is_available'], name='announcemen_is_avai_1e54f5_idx'),
        ),
        migrations.AddIndex(
            model_name='matingannouncement',
            index=models.Index(fields=['successful_matings'], name='announcemen_success_5fb1e5_idx'),
        ),
    ]
