# Generated by Django 5.1.5 on 2025-01-25 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Одобрено'), ('reject', 'Отклонено')], max_length=20, verbose_name='Действие')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_history', to='announcements.announcement', verbose_name='Объявление')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'История модерации',
                'verbose_name_plural': 'История модерации',
                'ordering': ['-created_at'],
            },
        ),
    ]
