# Generated by Django 5.1.5 on 2025-01-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_moderationhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModerationHistory',
        ),
    ]
