# Generated by Django 5.1.5 on 2025-01-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_lostfoundannouncement_animal_type_and_more'),
        ('announcements', '0003_delete_moderationhistory'),
    ]

    operations = [
    ]
