# Generated by Django 5.1.5 on 2025-01-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_merge_20250126_1927'),
        ('announcements', '0004_merge_20250126_1930'),
    ]

    operations = [
    ]
