# Generated by Django 5.1.5 on 2025-01-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostfoundannouncement',
            name='date_lost_found',
            field=models.DateField(verbose_name='Дата потери/находки'),
        ),
        migrations.AlterField(
            model_name='lostfoundannouncement',
            name='distinctive_features',
            field=models.TextField(verbose_name='Отличительные черты'),
        ),
        migrations.AlterField(
            model_name='lostfoundannouncement',
            name='type',
            field=models.CharField(choices=[('lost', 'Потеряно'), ('found', 'Найдено')], max_length=10, verbose_name='Тип'),
        ),
    ]
