# Generated by Django 5.0.2 on 2025-01-26 23:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_merge_20250126_2145'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lostfoundannouncement',
            name='announcemen_type_c4b954_idx',
        ),
        migrations.RenameField(
            model_name='lostfoundannouncement',
            old_name='has_microchip',
            new_name='microchipped',
        ),
        migrations.RemoveField(
            model_name='lostfoundannouncement',
            name='has_collar',
        ),
        migrations.RemoveField(
            model_name='lostfoundannouncement',
            name='has_tag',
        ),
        migrations.RemoveField(
            model_name='lostfoundannouncement',
            name='health_status',
        ),
        migrations.RemoveField(
            model_name='lostfoundannouncement',
            name='last_seen_details',
        ),
        migrations.RemoveField(
            model_name='lostfoundannouncement',
            name='last_seen_location',
        ),
        migrations.RemoveField(
            model_name='lostfoundannouncement',
            name='search_radius',
        ),
        migrations.RemoveField(
            model_name='lostfoundannouncement',
            name='temperament',
        ),
        migrations.AddField(
            model_name='lostfoundannouncement',
            name='collar_details',
            field=models.CharField(blank=True, max_length=255, verbose_name='Детали ошейника'),
        ),
        migrations.AddField(
            model_name='lostfoundannouncement',
            name='contacted_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None, verbose_name='Контакты с пользователями'),
        ),
        migrations.AddField(
            model_name='lostfoundannouncement',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Место пропажи/находки'),
        ),
        migrations.AddField(
            model_name='lostfoundannouncement',
            name='search_areas',
            field=models.JSONField(blank=True, null=True, verbose_name='Зоны поиска'),
        ),
        migrations.AddField(
            model_name='lostfoundannouncement',
            name='special_marks',
            field=models.JSONField(blank=True, null=True, verbose_name='Особые приметы'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='lostfoundannouncement',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка'), ('bird', 'Птица'), ('rodent', 'Грызун'), ('reptile', 'Рептилия'), ('fish', 'Рыба'), ('exotic', 'Экзотическое животное')], max_length=20, verbose_name='Вид животного'),
        ),
        migrations.AlterField(
            model_name='lostfoundannouncement',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Основной цвет'),
        ),
        migrations.AlterField(
            model_name='lostfoundannouncement',
            name='color_pattern',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип окраса'),
        ),
        migrations.AlterField(
            model_name='lostfoundannouncement',
            name='contact_phone',
            field=models.CharField(max_length=20, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='lostfoundannouncement',
            name='date_lost_found',
            field=models.DateTimeField(verbose_name='Дата и время пропажи/находки'),
        ),
        migrations.AlterField(
            model_name='lostfoundannouncement',
            name='distinctive_features',
            field=models.TextField(verbose_name='Отличительные черты'),
        ),
        migrations.AlterField(
            model_name='lostfoundannouncement',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='lostfoundannouncement',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='lostfoundannouncement',
            name='search_history',
            field=models.JSONField(blank=True, null=True, verbose_name='История поиска'),
        ),
        migrations.AlterField(
            model_name='lostfoundannouncement',
            name='size',
            field=models.CharField(choices=[('tiny', 'Очень маленький'), ('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Большой'), ('very_large', 'Очень большой')], max_length=20, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='lostfoundannouncement',
            name='type',
            field=models.CharField(choices=[('lost', 'Потеряно'), ('found', 'Найдено')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AddIndex(
            model_name='lostfoundannouncement',
            index=models.Index(fields=['type', 'animal_type'], name='announcemen_type_7c3a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfoundannouncement',
            index=models.Index(fields=['date_lost_found'], name='announcemen_date_lo_e897fb_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfoundannouncement',
            index=models.Index(fields=['location'], name='announcemen_locatio_d0a68b_idx'),
        ),
    ]
