# Generated by Django 5.0.2 on 2025-01-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_remove_lostfoundannouncement_announcemen_type_c4b954_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Местоположение'),
        ),
    ] 