# Generated by Django 5.1.5 on 2025-01-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_verificationdocument_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationdocument',
            name='document_type',
        ),
    ]
