# Generated by Django 5.1.5 on 2025-01-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_verificationdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocument',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Паспорт'), ('license', 'Лицензия'), ('certificate', 'Сертификат'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
