# Generated by Django 5.1.5 on 2025-01-26 14:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_verificationdocument_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Документ верификации', 'verbose_name_plural': 'Документы верификации'},
        ),
        migrations.RemoveField(
            model_name='verificationdocument',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='verificationdocument',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='document',
            field=models.FileField(upload_to='verification_documents/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Паспорт'), ('license', 'Лицензия'), ('certificate', 'Сертификат'), ('other', 'Другое')], max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
