# Generated by Django 5.1.5 on 2025-01-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_verificationdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False, verbose_name='Прошел онбординг'),
        ),
    ]
