# Generated by Django 5.1.5 on 2025-01-26 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_userprofile_is_onboarded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок проверки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL, verbose_name='Назначен модератору')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_queue', to='user_profile.verificationdocument', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Очередь модерации',
                'verbose_name_plural': 'Очереди модерации',
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
