# Generated by Django 5.0.2 on 2025-01-26 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_userprofile_is_onboarded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Последняя известная широта'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Последняя известная долгота'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['last_latitude', 'last_longitude'], name='user_profil_last_la_81f729_idx'),
        ),
    ]
