# Generated by Django 5.0.2 on 2025-01-26 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_add_location_fields'),
        ('user_profile', '0007_moderationqueue'),
    ]

    operations = [
    ]
