# Generated by Django 5.1.5 on 2025-01-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onetimecode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
