# Generated by Django 5.1.5 on 2025-01-30 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('match', 'Новое совпадение'), ('message', 'Новое сообщение'), ('status_update', 'Обновление статуса'), ('recommendation', 'Рекомендация'), ('lost_pet', 'Потерянное животное'), ('system', 'Системное уведомление')], max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_email_sent', models.BooleanField(default=False, verbose_name='Email отправлен')),
                ('is_push_sent', models.BooleanField(default=False, verbose_name='Push отправлен')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], max_length=20, verbose_name='Частота отправки')),
                ('scheduled_at', models.DateTimeField(verbose_name='Запланировано на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('notifications', models.ManyToManyField(related_name='batch', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пакет уведомлений',
                'verbose_name_plural': 'Пакеты уведомлений',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_matches', models.BooleanField(default=True, verbose_name='Новые совпадения')),
                ('email_new_messages', models.BooleanField(default=True, verbose_name='Новые сообщения')),
                ('email_status_updates', models.BooleanField(default=True, verbose_name='Обновления статуса')),
                ('email_recommendations', models.BooleanField(default=True, verbose_name='Новые рекомендации')),
                ('email_lost_pets', models.BooleanField(default=True, verbose_name='Потерянные животные')),
                ('push_new_matches', models.BooleanField(default=True, verbose_name='Новые совпадения')),
                ('push_new_messages', models.BooleanField(default=True, verbose_name='Новые сообщения')),
                ('push_status_updates', models.BooleanField(default=True, verbose_name='Обновления статуса')),
                ('push_recommendations', models.BooleanField(default=True, verbose_name='Новые рекомендации')),
                ('push_lost_pets', models.BooleanField(default=True, verbose_name='Потерянные животные')),
                ('email_frequency', models.CharField(choices=[('instant', 'Мгновенно'), ('daily', 'Раз в день'), ('weekly', 'Раз в неделю')], default='instant', max_length=20, verbose_name='Частота email уведомлений')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Начало тихого времени')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Конец тихого времени')),
                ('lost_pets_radius', models.PositiveIntegerField(default=10, verbose_name='Радиус уведомлений о потеряшках (км)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Push-токен')),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20, verbose_name='Тип устройства')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push-токен',
                'verbose_name_plural': 'Push-токены',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(fields=['user', 'scheduled_at'], name='notificatio_user_id_e5c8aa_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(fields=['is_sent'], name='notificatio_is_sent_0fd1ce_idx'),
        ),
        migrations.AddIndex(
            model_name='pushtoken',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_47d48f_idx'),
        ),
        migrations.AddIndex(
            model_name='pushtoken',
            index=models.Index(fields=['token'], name='notificatio_token_454efe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pushtoken',
            unique_together={('user', 'token')},
        ),
    ]
